name:           sd-utility
version:        '0.1.0.0'
synopsis:       Initial project template from stack
description:    Please see README.md
category:       Web
author:         Author name here
maintainer:     example@example.com
copyright:      2016 Author name here
license:        BSD3
github:         shlok/sd-utility

dependencies:
- base >=4.7 && <5
- bytestring
- cereal
- containers
- cpu
- mtl
- random
- scientific
- store
- streaming
- streaming-bytestring
- time

executables:
  sd-utility-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -O2
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sd-utility

library:
  source-dirs: src
  ghc-options: -Wall
  exposed-modules:
  - SD.Utility.AverageTrueRange
  - SD.Utility.Calendar
  - SD.Utility.Either
  - SD.Utility.Exception
  - SD.Utility.ExpMovingAverage
  - SD.Utility.IO
  - SD.Utility.MaxLengthSequence
  - SD.Utility.MinMaxSequence
  - SD.Utility.MovingAverage
  - SD.Utility.Random
  - SD.Utility.Read
  - SD.Utility.RelativeStrengthIndex
  - SD.Utility.Scientific
  - SD.Utility.Streaming

tests:
  sd-utility-test:
    main: TestSuite.hs
    source-dirs: test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sd-utility
    - QuickCheck
    - tasty
    - tasty-hunit
    - tasty-quickcheck
