name:           sd-utility
version:        '0.1.0.0'
synopsis:       Initial project template from stack
description:    Please see README.md
category:       Web
author:         Author name here
maintainer:     example@example.com
copyright:      2016 Author name here
license:        BSD3
github:         shlok/sd-utility

dependencies:
- base >=4.7 && <5
- scientific >=0.3.5.1
- time >=1.6.0.1

library:
  source-dirs: src
  default-extensions:
  - OverloadedStrings
  ghc-options: -Wall
  exposed-modules:
  - SD.Utility.Either
  - SD.Utility.Calendar
  - SD.Utility.Exception
  - SD.Utility.IO
  - SD.Utility.Read
  - SD.Utility.Scientific

tests:
  sd-utility-test:
    main: TestSuite.hs
    source-dirs: test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sd-utility
    - tasty >=0.11.2.1
    - tasty-hunit >=0.9.2
    - tasty-quickcheck >=0.8.4
